In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split


df = pd.read_csv("../data/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [59]:
df.shape

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df.describe()

df.head()

df["YearsAtCompany"].unique()

In [ ]:
sns.boxplot(x="Attrition", y="YearsAtCompany", data=df)
plt.show()



pd.crosstab(df["BusinessTravel"], df["Attrition"], normalize="index")

In [ ]:
df["Attrition"].unique()

df["BusinessTravel"].unique()

df["Department"].unique()

df["StandardHours"].unique()

df["EmployeeCount"].unique()

df["StockOptionLevel"].unique()

df["TrainingTimesLastYear"].unique()

df["WorkLifeBalance"].unique()

In [ ]:
df["Attrition"].value_counts().plot(kind="bar")

# df["BusinessTravel"].value_counts()

# df["Department"].value_counts()

plt.show()

In [ ]:
sns.boxplot(
    x="Attrition",
    y="MonthlyIncome",
    data=df
)

plt.show()

pd.crosstab(df["OverTime"], df["Attrition"], normalize="index")

df.head()

In [ ]:

# Feature Classification 
print(df.columns)

identifier_features =  "EmployeeNumber"

target = "Attrition"

numerik_features = [
    "Age",
    "DistanceFromHome",
    "DailyRate",
    "HourlyRate",
    "MonthlyIncome",
    "MonthlyRate",
    "NumCompaniesWorked",
    "PercentSalaryHike",
    "TotalWorkingYears",
    "TrainingTimesLastYear",
    "YearsAtCompany",
    "YearsInCurrentRole",
    "YearsSinceLastPromotion",
    "YearsWithCurrManager"
]

ordinal_features = [
    "JobLevel",
    "Education",
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "JobSatisfaction",
    "PerformanceRating",
    "RelationshipSatisfaction",
    "StockOptionLevel",
    "WorkLifeBalance"
]

nominal_features = [
    "BusinessTravel",
    "Department",
    "EducationField",
    "Gender",
    "JobRole",
    "MaritalStatus",
    "OverTime",
]

drop_columns = [
    "EmployeeCount",
    "Over18",
    "StandardHours"
]

In [ ]:
#EDA

df[numerik_features].hist(figsize=(18,12))
plt.tight_layout()
plt.show()

In [ ]:
corr = df[numerik_features].corr()

plt.figure(figsize=(12,10))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.show()

In [ ]:
X = df.drop("Attrition", axis=1)
y = df[["Attrition"]]

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

df["Education"].head()

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

#Membuat satu object scaler yang nanti menyimpan hasil pembelajaran data training, lalu menggunakan scaler yang sama untuk training dan testing
scaler = StandardScaler()

#Menyimpan data (mean, standarddeviasion untuk setiap fitur numerik)
# Tidak menggunakan fit pada X_test karena kita tidak ingin data tes belajar langsung
scaler.fit(X_train[numerik_features])

scaler.mean_
scaler.scale_

#Menggunakan data dari scaler numerik tadi untuk mengubah numerik features 
X_train_scaled = scaler.transform(X_train[numerik_features])
X_test_scaled = scaler.transform(X_test[numerik_features])

#Mengubah menjadi dataframe, karena default scikitlearn scaler adalah numpy.ndarray, bukan pandas df
X_train_scaled = pd.DataFrame(X_train_scaled, columns=numerik_features, index=X_train.index)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=numerik_features, index=X_test.index)

# X_train_scaled.head()
# X_test_scaled.head()

X_test_scaled.mean()

#pandas.std menggunakn sample std (ddof=1), sedangkan StandardScaler menggunakan ddof=0 (maka dari itu nilainya sedikit di atas 1)

In [ ]:
print("Mean scaler: ")
print(scaler.mean_)

print("\n Mean X_train_scaled: ")
print(X_train_scaled.mean())

print("\n Std X_train_scaled: ")
print(X_train_scaled.std())

X_train_scaled.head()

In [ ]:
# handleunknown berguna untuk jika mempunyai kategori baru yang belum pernah ditraining, maka akan dihandle sebagai kategori tidak memiliki kolom aktif
# OneHotEncoder memiliki bawaan sparsematrix, yaitu format hemat memori duntuk data dengan banyak nilai 0
# Karena data kita kecil, lebih nyaman jika kita tidak gunakan dan pakai array biasa agar bisa dijadikan datafram


encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoder.fit(X_train[nominal_features])

# Encoder memecah masing masing menjadi kolom biner
# Apakah karyawan ini bagian ddari department sales, hasilnya bakal ngeluarin 1 0 
encoder.get_feature_names_out(nominal_features)

In [58]:
X_train_encoded = encoder.transform(X_train[nominal_features])
X_test_encoded = encoder.transform(X_test[nominal_features])

X_train_encoded = pd.DataFrame(X_train_encoded, 
                               columns=encoder.get_feature_names_out(nominal_features),
                               index=X_train.index)
X_test_encoded = pd.DataFrame(X_test_encoded, 
                              columns=encoder.get_feature_names_out(nominal_features),
                              index=X_test.index)

X_train_encoded.head()

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
1097,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
727,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
254,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1175,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1341,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0